---
# ========================================
config-version: 2 # ¡Don't Change This!
# ========================================
# Permissions:
# /broadcast send = broadcast.command.send
# /broadcast help = broadcast.command.help
# ========================================
# Variables:
# {online} = Get Players in Server 
# {name} = Get Player name
# {money} = Get money from players (Requires EconomyAPI)
# ========================================
prefix: "§a[Server]" # Default: "§a[Server]"
# ========================================
message_interval: 30  # Default: 30
# ========================================
# To add more messages add - and "message"
messages:
- "§7Playing now in server: §6{online}"
- "§7Your money on the server is: §6{money}"
- "§7This is what your nickname would look like: §l§6RANK1 §r§f{name}§7, if you bought rank Rank1."
- "§7Suscribe to §6YoSoyJony §7:D"
- "§7Follow on §6https://github.com/JonyGamesYT9"
- "§7Buy a rank in: §6shop.latammc.cf"
- "§7Thanks for playing in: §6Latam.cf:19132"
# ========================================
# Example usage:
# per-world-messages:
#  world_name:
#  - "Hello players in world :)"
per-world-messages:
 world:
 - "Hi"
 world2:
 - "Hello"
# ========================================
...
