---
# ========================================
config-version: 5 # ¡Don't Change This!
# ========================================
# Permissions:
# /broadcast send = broadcast.command.send
# /broadcast help = broadcast.command.help
# ========================================
# Variables:
# {online} = Get Players in Server 
# {name} = Get Player name
# ========================================
prefix: "§a[Server]" # Default: "§a[Server]"
# ========================================
message_interval: 30  # Default: 30
# ========================================
# To add more messages add - and "message"
messages:
- "§7Playing now in server: §6{online}"
- "§7This is what your nickname would look like: §l§6RANK1 §r§f{name}§7, if you bought rank Rank1."
- "§7Follow on §6https://github.com/JonyGamesYT9"
# ========================================
...
